### ISSUE TITLE
Capstone Project - Module 4 - Catalog My Things

### ISSUE THREAD

**Issue by jcmunav63** [jcmunav63/catalog-my-things#36]
This is the Kanban Board for the Capstone Team Project of Module 4 - Catalog My Things. It's a project for developing a Ruby app using OOP and Unit Testing.

In its description, paste a link to your GitHub project:
https://github.com/jcmunav63/catalog-my-things/projects/1

Add a note telling the reviewer how many people there are on your team:
Hello, I hope you are having a great day.
We are two teammates, the first one is me @jcmunav63  and the second one is @Alejandroq12.

Add a note telling the reviewer which team member was assigned to tasks listed for: 
Team member #1 @Alejandroq12 
Team member #2 @jcmunav63 
Team member #3 @jcmunav63 @Alejandroq12 Both of us because we are only two.
Team member #4 Does not apply

Have a good day.

**Comment by danmainah** [comment]
Hi @jcmunav63 and @Alejandroq12 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Used the current format to setup the kanban board.
✔️ Used he [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md#group-task). to add tasks to the kanban board.

# Required Changes ♻️

- [x] @Team Great work distributing tasks among yourselves, however, there is a great difference in time allocated for @Alejandroq12 (22.5) verses @jcmunav63 (16.25), this is because in some equal tasks eg creating schema file in tasks [#15](https://github.com/jcmunav63/catalog-my-things/issues/21)  and [#24](https://github.com/jcmunav63/catalog-my-things/issues/26) tasks @Alejandroq12 has more time allocated than @jcmunav63 , kindly consider fixing the issue to reduce the time difference, and esnure fairness in time distribution among members.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Alejandroq12** [comment]
Thank you  for your feedback. We fixed it.
Have a good day.

**Comment by Olamarx** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>
## Highlights
- Fair distribution of tasks ✔️

## Optional suggestions
- [OPTIONAL] I would encourage you to remove the third tag of team member 3 since you guys are two. 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alejandroq12** [comment]
Thank you very much for yout feedback.
